### ISSUE TITLE
[Improvement] Simplify the translation of K-Box in other languages

### ISSUE THREAD

**Issue by shenriod** [k-box/k-box#114]
### Short Description of the issue

Currently the translation of K-Box strings to other languages is quite complex and can lead to mistakes, especially for translators not really proficient with programming languages.

Also, it is very difficult to follow all PRs and know where there are translations missing.

Therefore the translation should be externalised to a simpler platform (Transifex?) to facilitate further translations in additional languages and to better keep the existing translations up-to-date

**Comment by avvertix** [comment]
When the issue was opened the changes were managed differently. Currently the localization structure follows the Laravel's baseline. 

We checked [Transifex](https://www.transifex.com/), [Lokalize](https://lokalise.com/), [Crowdin](https://crowdin.com/) as hosted services and [Traduora](https://github.com/traduora/traduora) as self-hosted open source solution. Considering the available options and the eligibility requirements for Open Source software we think we are not ready yet to apply to those platforms. We will look again for alternatives in the next months.
