### ISSUE TITLE
URL format for the copyright owner [0.20]

### ISSUE THREAD

**Issue by shenriod** [k-box/k-box#17]
Why is this URL considered not valid?

![capture](https://user-images.githubusercontent.com/23653367/35729276-f56d9856-082f-11e8-8119-47ef9e8c6c6c.PNG)

The system should accept URL without "http", to make it more convenient for the users

PS: same issue on the user profile page:
![capture](https://user-images.githubusercontent.com/23653367/35795091-dab0246a-0a79-11e8-8134-876207aa194f.PNG)

**Comment by avvertix** [comment]
The URL are not considered valid because they lack the schema, which can be `http` or `https`.

Since copy the URL using the browser user interface (url bar, right click menu) already copies the schema, this only affects users that type manually the url. Typing manually the URL is also error prone to other syntax errors that cannot be prevented (or for which the mitigation is complex). Therefore I will not consider this as being an issue for now.
