### ISSUE TITLE
Add templates for custom licenses

### ISSUE THREAD

**Issue by shenriod** [k-box/k-box#37]
### Short Description of the issue

K-Box supports licensing of documents from 0.20 and comes packaged with a set of CC licenses.

It would however be nice if the users could also add their own licenses. It can be that a company / institution wishes to publish documents under a specific license that makes sense in their context but that shouldn´t be included in the K-Box sourcecode.

### Expected behavior

A template for custom licenses (name, short text, full legal text, icon) should be available to the admins of the K-box.

### Steps to reproduce the incorrect behavior

N/A

### General information

Version of your K-Box: 0.20

URL of the page where the problem has occured: N/A

Type and version of your browser: N/A

In what language are you using your K-Box? N/A

**Comment by avvertix** [comment]
We selected a set of licenses that fits the possible content of the K-Box, which is more likely to be text and images. Currently CC is the most agreed license for text and images and is accepted globally.
In other words this first implementation has the possibility to clarify on the copyright and how the document can be used.

Behind the scenes the list of selectable licenses is not fixed. This file https://github.com/k-box/k-box/blob/master/packages/licenses/assets/licenses.json and the folder in which is contained make things extensible. The file can be replaced during deployment.

The change of the available licenses is not user comfortable, but we didn't see a huge use case to make this configuration on the UI. In other words we think it will not be used so may times.

If you have knowledge of scenarios in which this feature will be used more times it will be good. Otherwise you can also suggest which licenses from https://spdx.org/licenses/ you would like to see included.

**Comment by shenriod** [comment]
I don't have a concrete use case yet. But I was more thinking of the case where an institution has developed its own terms of use for its published documents, that are extremely specific and do not fit in the usual and widely accepted licenses.

But if it is possible to configure additional licenses in the json file for each deployment, I guess this is sufficient for now. But I guess that this customised json file should then be taken care of manually every time a new version is deployed?

**Comment by avvertix** [comment]
> But I guess that this customised json file should then be taken care of manually every time a new version is deployed?

Is a thing that the technician that is performing the deploy should take care to not override. We currently use only [Docker](https://www.docker.com/), therefore this file (and folder) can be mapped inside the container that runs the K-Box. This deployment technique should ensure that K-Box updates do not interfere with the customization.

**Comment by shenriod** [comment]
Ok, then I guess it is sufficiently flexible for now, until we bump into a concrete use case. Will close the issue.

Thanks!
