### ISSUE TITLE
Link in the text of a license to be opened in a new tab

### ISSUE THREAD

**Issue by shenriod** [k-box/k-box#56]
### Short Description of the issue

This bug has been resolved: https://github.com/k-box/k-box/issues/19

But if there is a link in the text of the license, it opens in the same window / tab

### Expected behavior

Should open in a new tab

### Steps to reproduce the incorrect behavior

1. On the edit page of document, click on "Help me to choose a license"

2. Scroll down to Creative Commons Attribution 4.0 International

3. Click on "appropriate credit"

### General information

Version of your K-Box: 0.20

URL of the page where the problem has occured:

Type and version of your browser: Firefox 58, IE11

In what language are you using your K-Box? 

### Screenshots

![capture](https://user-images.githubusercontent.com/23653367/37082324-1c999d7e-220e-11e8-968f-149031031eb8.PNG)

**Comment by avvertix** [comment]
The license explanation text is written in Markdown. In order to make links opening in a new tab a Markdown parser plugin needs to be created. The plugin should identify links pointing to a different domain then the one hosting the K-Box and add the `target="_blank"` attribute to the `anchor` element.

**Comment by avvertix** [comment]
Should be fixed by #272
