### ISSUE TITLE
Re-upload a file that is in someone's trash

### ISSUE THREAD

**Issue by shenriod** [k-box/k-box#7]
I am translating the help page in French but one behavior is not clear to me:

If User A uploads a document and then moves it to trash (but does NOT delete it permanently), will user B be able to re-upload the same document?

If not, what information will user B receive, in order to identify in whose trash it is? It can otherwise be very frustrating for user B and it will also be a hassle for the librarian to identify where the "1st version" of the file is hiding

Can you clarify the behavior so that I can accordingly make it clear in the help page?

Thanks!

**Comment by avvertix** [comment]
> If User A uploads a document and then moves it to trash (but does NOT delete it permanently), will user B be able to re-upload the same document?

The current behavior for document upload is to verify the existence of the exact same version (based on the content hash). The trash plays also a role as it is considered a valid location (trashed files can be restored and therefore needs to still respect the uniqueness policy), therefore it is indicated that the file already exists with the name of the file or the title of the document. In general cases the title of the document is provided as the File is described by a Document Descriptor. In some rare cases only the File original name will be outputted in the [already existing message](https://github.com/k-box/k-box/blob/master/app/Exceptions/FileAlreadyExistsException.php)

This is different for video uploads using the video uploader (the new experimental upload mechanism): with this tool the upload of the same file more than 1 time is allowed.

The rationale is to that verify that a video has already been upload is difficult (two videos might be the same, but at different resolution) and is not possible until the whole file is uploaded. If we let upload the whole, e.g. 1GB video, and then delete it because it already exists it will generate a waste of bandwidth and user time.

Please be aware that with the video uploader ability to upload multiple times the same file duplication in search results might occur.

**Comment by shenriod** [comment]
Thanks !

But what is the foreseen scenario in my example? Can user B know in whose's
Trash the first version is?

I am just worried that user B will only see that he cannot upload a doc,
without knowing where the existing one is, since he cannot see user A's
trash.

Same is valid for the personal collections: if I upload a doc to my
personal collection, user B won't be able to upload again the same doc, but
he also cannot see my personal collection.

Do you see this problem as well or did I misunderstand something?

**Comment by avvertix** [comment]
> Can user B know in whose's Trash the first version is?

No, currently not

> I am just worried that user B will only see that he cannot upload a doc,
> ... f I upload a doc to my personal collection, user B won't be able to upload again the same doc, but he also cannot see my personal collection.

This is what currently happens

> Do you see this problem as well or did I misunderstand something?

I actually see the problem, but the overall "Already exists check" is a complex feature. Exposing that a file is in someone's trash is a privacy leaking, like stating that is personal to some user. On the other side the users don't want to see duplication in search results (with duplications I mean the same document listed twice). The compromise was to limit the upload of a document that already exists, but is clearly more acceptable in a shared scenario, where documents are mostly shared accross all users.

**Comment by shenriod** [comment]
Ok thanks, the situation is clear!

Then this case is closed for now but I think we should think again all
together what the behaviour should be, because the current one makes lots
of sense in 99% of the cases but can create lots of user's frustration in
1% of cases.

Maybe: when a doc is in the trash, it is no longer considered as "in the
system", so that user B can upload it again. And if user A tries to get the
doc out of his trash, only then the system will say "this doc already
exists here .... ." I think that would be much more transparent .

But this still leaves open the case of docs in private collections. To be
brainstormed...

**Comment by avvertix** [comment]
yep, a general question here should be resolved: "_is better to have duplication of same files or to stick with blocking what is already existent?_".

> Maybe: when a doc is in the trash, it is no longer considered as "in the system", so that user B can upload it again. And if user A tries to get the doc out of his trash, only then the system will say "this doc already exists here .... ." I think that would be much more transparent .

I think this will not solve the point, as move the problem on the restore of the file, where the same generic already exists message is used in case a document is in someone's personal area (again the privacy problem, which I think it should be respected)

**Comment by shenriod** [comment]
> I think this will not solve the point, as move the problem on the restore of the file, where the same generic already exists message is used in case a document is in someone's personal area (again the privacy problem, which I think it should be respected)

Right... this needs some more thinking... I will close the issue for now and we can brainstorm later, in the frame of the global roadmap of the System

Thanks!
